### ISSUE TITLE
Add obtainable items to overview for sets

### ISSUE THREAD

**Issue by fewhnhouse** [fewhnhouse/eso-build-editor-frontend#128]
Make sure that in overview, people can see what type the set is available for (weapons, jewelry, armor)

**Comment by khuusko** [comment]
New small component to render icons to indicate what items are obtainable. If the set is not craftable (so not all items are obtainable), render small icons for armor, jewelry, weapons respectively. Both in sets overview card AND the set menu list (in overview and build editor).
