### ISSUE TITLE
Make it possible to browse racial passives and skill lines?

### ISSUE THREAD

**Issue by khuusko** [fewhnhouse/eso-build-editor-frontend#71]
Like a "database browsing" feature, David was complaining that finding up-to-date information is impossible

**Comment by fewhnhouse** [comment]
yeah absolutely, wanted to make a seperate screen for it anyway

**Comment by fewhnhouse** [comment]
This is why i wanted an "overview" card on the not-logged in screen for home. from there, you are supposed to be able to search for sets and skills
