### ISSUE TITLE
Build copy does not actually copy references such as sets and skills.

### ISSUE THREAD

**Issue by fewhnhouse** [fewhnhouse/eso-build-editor-frontend#81]
When copying and changing sets / builds, they get changed in the parent aswell because copying does currently not respect subfields.

**Comment by fewhnhouse** [comment]
@khuusko please test this, should be fixed on master (not production)

**Comment by fewhnhouse** [comment]
also with buf food, traits etc.

**Comment by khuusko** [comment]
Succesfully copied a build - then edited name, race, food buff, mundus, some skills and sets, saved, and it did not affect the other build (can't actually say if it was the copy or the original that I edited but nevertheless)
