### ISSUE TITLE
Maelstrom resto bonus not bolded when staff is slotted

### ISSUE THREAD

**Issue by khuusko** [fewhnhouse/eso-build-editor-frontend#82]
Noticed in build review, requires further testing if it's visible everywhere and if it only counts as 1 item in this case

**Comment by fewhnhouse** [comment]
yeah bolding is still not perfect anyway. it also calculates both boni from front-and backbar together instead of seperately (or even instead of only the one that has the set that is currently selected which would be the best option for now)
